from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Device", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120, unique=True))]),
        migrations.CreateModel(name="Station", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(default="PUB-TV", max_length=120)), ("timezone", models.CharField(default="America/Detroit", max_length=64))]),
        migrations.CreateModel(name="Show", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("code", models.SlugField(max_length=40)), ("producer_name", models.CharField(blank=True, max_length=160)), ("producer_contact", models.CharField(blank=True, max_length=240)), ("station", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shows", to="operations.station"))], options={"constraints": [models.UniqueConstraint(fields=("station", "code"), name="unique_station_show_code")]}),
        migrations.CreateModel(name="Episode", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("producer_id", models.CharField(blank=True, max_length=120)), ("intended_air_order", models.PositiveIntegerField(blank=True, null=True)), ("intended_premiere_date", models.DateField(blank=True, null=True)), ("runtime_seconds", models.PositiveIntegerField(blank=True, null=True)), ("status", models.CharField(choices=[("pending", "Pending"), ("previously_scheduled", "Previously scheduled")], default="pending", max_length=24)), ("received_at", models.DateTimeField(blank=True, null=True)), ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="operations.show"))]),
        migrations.CreateModel(name="MediaAsset", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("label", models.CharField(max_length=160)), ("kind", models.CharField(choices=[("source", "Source"), ("encoded", "Encoded")], max_length=16)), ("version", models.CharField(default="v1", max_length=80)), ("runtime_seconds", models.PositiveIntegerField(blank=True, null=True)), ("smb_reference", models.CharField(blank=True, max_length=300)), ("episode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assets", to="operations.episode"))]),
        migrations.CreateModel(name="Delivery", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("method", models.CharField(choices=[("dropbox", "Dropbox"), ("email", "Email"), ("smb", "SMB")], max_length=16)), ("reference", models.CharField(max_length=300)), ("notified_at", models.DateTimeField(blank=True, null=True)), ("received_at", models.DateTimeField(blank=True, null=True)), ("notes", models.TextField(blank=True)), ("episodes", models.ManyToManyField(blank=True, related_name="deliveries", to="operations.episode"))]),
        migrations.CreateModel(name="Occurrence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("item_type", models.CharField(choices=[("episode", "Episode"), ("media", "Media"), ("station_id", "Station Id"), ("psa", "Psa"), ("filler", "Filler"), ("live", "Live")], max_length=16)), ("label", models.CharField(max_length=160)), ("starts_at", models.DateTimeField()), ("planned_duration_seconds", models.PositiveIntegerField()), ("status", models.CharField(choices=[("planned", "Planned"), ("cancelled", "Cancelled"), ("preempted", "Preempted"), ("rescheduled", "Rescheduled")], default="planned", max_length=16)), ("reason", models.TextField(blank=True)), ("revision", models.PositiveIntegerField(default=1)), ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="operations.mediaasset")), ("episode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="occurrences", to="operations.episode")), ("show", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="occurrences", to="operations.show")), ("station", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="occurrences", to="operations.station"))]),
        migrations.CreateModel(name="RecurrenceSlot", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("weekday", models.PositiveSmallIntegerField(choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")])), ("start_time", models.TimeField()), ("duration_seconds", models.PositiveIntegerField()), ("active_from", models.DateField(blank=True, null=True)), ("active_until", models.DateField(blank=True, null=True)), ("show", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="operations.show")), ("station", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="operations.station"))]),
        migrations.CreateModel(name="WeeklyEpisodeAssignment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("week_start", models.DateField()), ("selection_type", models.CharField(choices=[("premiere", "New premiere"), ("rerun", "Selected older rerun"), ("none", "No program")], max_length=16)), ("episode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="operations.episode")), ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="weekly_assignments", to="operations.show"))], options={"constraints": [models.UniqueConstraint(fields=("show", "week_start"), name="unique_show_week")]}),
        migrations.CreateModel(name="Preparation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source_available", models.CharField(choices=[("yes", "Yes"), ("no", "No"), ("na", "N/A")], default="no", max_length=12)), ("ame_preset", models.CharField(blank=True, max_length=160)), ("ftp_output_device", models.CharField(blank=True, max_length=200)), ("library_registration", models.CharField(blank=True, max_length=200)), ("slot_assignment", models.CharField(blank=True, max_length=200)), ("uploaded_schedule_revision", models.CharField(blank=True, max_length=120)), ("provenance", models.TextField(blank=True)), ("occurrence", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preparation", to="operations.occurrence"))]),
        migrations.CreateModel(name="UploadedScheduleRevision", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("external_reference", models.CharField(blank=True, max_length=200)), ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)), ("state", models.CharField(choices=[("active", "Active"), ("superseded", "Superseded"), ("invalidated", "Invalidated")], default="active", max_length=16)), ("supersession_reason", models.TextField(blank=True)), ("device", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.device"))]),
        migrations.CreateModel(name="OccurrenceProgramming", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("confirmed_at", models.DateTimeField(default=django.utils.timezone.now)), ("note", models.TextField(blank=True)), ("device", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.device")), ("occurrence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="programming", to="operations.occurrence"))]),
        migrations.CreateModel(name="AiringEvidence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("reported", "Reported/observed"), ("log_verified", "Log verified")], max_length=20)), ("source", models.CharField(max_length=200)), ("aired_at", models.DateTimeField()), ("notes", models.TextField(blank=True)), ("occurrence", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="airing_evidence", to="operations.occurrence"))]),
        migrations.AddField(model_name="preparation", name="source_available_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="source_available_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="source_available_provenance", field=models.TextField(blank=True)),
        migrations.AddField(model_name="preparation", name="ame_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="ame_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="ame_provenance", field=models.TextField(blank=True)),
        migrations.AddField(model_name="preparation", name="ftp_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="ftp_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="ftp_provenance", field=models.TextField(blank=True)),
        migrations.AddField(model_name="preparation", name="library_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="library_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="library_provenance", field=models.TextField(blank=True)),
        migrations.AddField(model_name="preparation", name="slot_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="slot_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="slot_provenance", field=models.TextField(blank=True)),
        migrations.AddField(model_name="preparation", name="upload_actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="preparation", name="upload_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="preparation", name="upload_provenance", field=models.TextField(blank=True)),
        migrations.CreateModel(name="UploadedOccurrenceCoverage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("occurrence_revision", models.PositiveIntegerField(default=1)), ("occurrence", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="operations.occurrence")), ("upload", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="operations.uploadedschedulerevision"))], options={"constraints": [models.UniqueConstraint(fields=("upload", "occurrence"), name="unique_upload_occurrence")]}),
        migrations.AddField(model_name="uploadedschedulerevision", name="occurrences", field=models.ManyToManyField(blank=True, related_name="uploaded_revisions", through="operations.UploadedOccurrenceCoverage", to="operations.occurrence")),
        migrations.AddField(model_name="airingevidence", name="created_at", field=models.DateTimeField(default=django.utils.timezone.now)),
        migrations.AddField(model_name="airingevidence", name="actor", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="airingevidence", name="supersedes", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="corrections", to="operations.airingevidence")),
        migrations.AddField(model_name="occurrence", name="weekly_assignment", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="occurrences", to="operations.weeklyepisodeassignment")),
        migrations.CreateModel(name="AuditEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("actor", models.CharField(default="owner", max_length=120)), ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)), ("action", models.CharField(max_length=40)), ("entity", models.CharField(max_length=80)), ("entity_id", models.PositiveIntegerField(blank=True, null=True)), ("revision", models.PositiveIntegerField(blank=True, null=True)), ("summary", models.TextField())]),
    ]
