# Generated by Django 5.2.17 on 2026-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_asset_preparation_ame_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='carry_forward_unassigned_episodes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyepisodeassignment',
            name='is_automatic_carry_forward',
            field=models.BooleanField(default=False),
        ),
    ]
