# Generated by Django 5.2.17 on 2026-10-02 00:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_ultranexus_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='base_bin_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='base_bin_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='command_port',
            field=models.PositiveIntegerField(default=23),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='command_secret_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='command_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='activationevidence',
            name='status',
            field=models.CharField(choices=[('schedule_transferred', 'Schedule Transferred'), ('activation_requested', 'Activation Requested'), ('activation_acknowledged', 'Activation Acknowledged'), ('activation_observed', 'Activation Observed'), ('winlgx_reconstructed', 'Winlgx Reconstructed'), ('airing_observed', 'Airing Observed'), ('rolled_back', 'Rolled Back'), ('ambiguous', 'Ambiguous'), ('failed', 'Failed'), ('confirmed', 'Confirmed'), ('observed', 'Observed')], max_length=32),
        ),
        migrations.CreateModel(
            name='ScheduleDeliveryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('prepared', 'Prepared'), ('staged', 'Staged'), ('promotion_started', 'Promotion Started'), ('schedule_transferred', 'Schedule Transferred'), ('activation_requested', 'Activation Requested'), ('activation_acknowledged', 'Activation Acknowledged'), ('activation_observed', 'Activation Observed'), ('ambiguous', 'Ambiguous'), ('rollback_started', 'Rollback Started'), ('rollback_ambiguous', 'Rollback Ambiguous'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='prepared', max_length=32)),
                ('approval_hash', models.CharField(max_length=64)),
                ('base_hash', models.CharField(max_length=64)),
                ('rollback_path', models.CharField(blank=True, max_length=500)),
                ('rollback_hash', models.CharField(blank=True, max_length=64)),
                ('staging_path', models.CharField(blank=True, max_length=500)),
                ('remote_backup_path', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(default='owner', max_length=120)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to='operations.artifactrevision')),
                ('publication_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to='operations.schedulepublicationbatch')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_delivery_operations', to='operations.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ('prepared', 'staged', 'promotion_started', 'schedule_transferred', 'activation_requested', 'ambiguous', 'rollback_started', 'rollback_ambiguous'))), fields=('target',), name='unique_active_schedule_delivery_target')],
            },
        ),
    ]
