# Generated by Django 5.2.17 on 2026-10-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_ultranexustargetsettings_base_bin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencerevisionselection',
            name='operation',
            field=models.CharField(choices=[('add', 'Add'), ('move', 'Move'), ('replace', 'Replace'), ('delete', 'Delete')], default='add', max_length=12),
        ),
        migrations.AddField(
            model_name='occurrencerevisionselection',
            name='source_bin_record_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='occurrencerevisionselection',
            name='source_bin_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
