# Generated by Django 5.2.17 on 2026-10-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_occurrencerevisionselection_operation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledeliveryoperation',
            name='unique_active_schedule_delivery_target',
        ),
        migrations.AddConstraint(
            model_name='scheduledeliveryoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('prepared', 'staged', 'promotion_started', 'schedule_transferred', 'activation_requested', 'activation_acknowledged', 'ambiguous'))), fields=('target',), name='unique_active_schedule_delivery_target'),
        ),
    ]
