# Generated by Django 5.2.17 on 2026-10-02 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Q


def reserve_existing_bindings(apps, schema_editor):
    Binding = apps.get_model('operations', 'MediaBinding')
    Allocation = apps.get_model('operations', 'MediaIdAllocation')
    for binding in Binding.objects.using(schema_editor.connection.alias).all().iterator():
        if binding.media_id_uint16 is None and binding.resource_reference_uint32 is None:
            continue
        Allocation.objects.using(schema_editor.connection.alias).create(
            target_id=binding.target_id,
            media_id_uint16=binding.media_id_uint16,
            resource_reference_uint32=binding.resource_reference_uint32,
            casefold_key=binding.casefold_key or f'historical-binding-{binding.pk}',
            media_hash='',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_remove_scheduledeliveryoperation_unique_active_schedule_delivery_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaIdAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id_uint16', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_reference_uint32', models.PositiveBigIntegerField(blank=True, null=True)),
                ('casefold_key', models.CharField(max_length=255)),
                ('media_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_id_allocations', to='operations.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'media_id_uint16'), condition=Q(media_id_uint16__isnull=False), name='unique_target_allocated_media_id'), models.UniqueConstraint(fields=('target', 'resource_reference_uint32'), condition=Q(resource_reference_uint32__isnull=False), name='unique_target_allocated_resource_ref'), models.UniqueConstraint(fields=('target', 'casefold_key'), name='unique_target_allocated_media_name')],
            },
        ),
        migrations.RunPython(reserve_existing_bindings, migrations.RunPython.noop),
    ]
