# Generated by Django 5.2.17 on 2026-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_permanent_media_id_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='ame_preset_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='bin_template_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='controller_family',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='ffmpeg_profile_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='media_profile',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='nmg_template_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='output_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='profile_identity_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='qualification_evidence_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ultranexustargetsettings',
            name='qualification_status',
            field=models.CharField(choices=[('open', 'Open'), ('passed', 'Passed'), ('blocked', 'Blocked')], default='open', max_length=16),
        ),
    ]
