# Generated by Django 5.2.17 on 2026-10-02 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_schedulepublicationbatch_preparation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationbatch',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation_batches', to='operations.show'),
        ),
        migrations.AddField(
            model_name='preparationbatch',
            name='submission_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='preparationbatchitem',
            name='execution_status',
            field=models.CharField(choices=[('pending', 'Queued'), ('encoding', 'Encoding'), ('validating', 'Validating'), ('transferring', 'Transferring'), ('verifying', 'Verifying'), ('ready', 'Ready'), ('blocked', 'Needs attention'), ('failed', 'Needs attention')], default='pending', max_length=20),
        ),
    ]
