# Generated by Django 5.2.17 on 2026-10-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_independent_media_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepublicationbatch',
            name='review_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PublicationCycleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_snapshot', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_cycle_selections', to='operations.mediaasset')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_cycle_selections', to='operations.weeklyepisodeassignment')),
                ('preparation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_cycle_selections', to='operations.preparationbatchitem')),
                ('publication_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_selections', to='operations.schedulepublicationbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication_batch', 'assignment'), name='unique_publication_cycle_selection')],
            },
        ),
    ]
