# Generated by Django 5.2.17 on 2026-10-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_publication_cycle_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledeliveryoperation',
            name='state',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('staged', 'Staged'), ('promotion_started', 'Promotion Started'), ('schedule_transferred', 'Schedule Transferred'), ('activation_requested', 'Activation Requested'), ('activation_acknowledged', 'Activation Acknowledged'), ('activation_observed', 'Activation Observed'), ('ambiguous', 'Ambiguous'), ('rollback_started', 'Rollback Started'), ('rollback_ambiguous', 'Rollback Ambiguous'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='prepared', max_length=32),
        ),
    ]
